### ISSUE TITLE
Reset autoplay timeout after user navigation

### ISSUE THREAD

**Issue by odahcam** [sheikalthaf/ngu-carousel#87] opened 2018-09-17 22:38 UTC
Sometimes, the carousel changes slides right after I navigate trough the navigation arrows.

**Comment by sheikalthaf** [comment] 2018-09-18 16:57
Duplicate of #25

**Comment by sheikalthaf** [comment] 2018-09-30 08:54
@odahcam Fixed the issue in latest build. Thanks

**Closed by sheikalthaf** 2018-09-30 08:54 UTC
Labels: bug:component
