### ISSUE TITLE
Memory leaking wile using ngu-carousel

### ISSUE THREAD

**Issue by sarnecki-cic** [sheikalthaf/ngu-carousel#103] opened 2018-10-05 05:59 UTC
The problem is when I use ngu-carousel with data that is constantly changing.
After a while the app and the whole browser is stucked. It seems like the ngu-carousel stores all the data inside and it's crashing the app.

**Comment by sheikalthaf** [comment] 2018-10-05 16:50
Duplicate of #104

**Comment by sheikalthaf** [comment] 2018-10-05 16:51
@sarnecki-cic Thanks for reporting fixed this issue and will push the update. Thanks

**Comment by sheikalthaf** [comment] 2018-10-06 12:28
@sarnecki-cic This isssue is fixed. Please check release.

Thanks

**Closed by sheikalthaf** 2018-10-06 12:28 UTC
Labels: bug, duplicate
