### ISSUE TITLE
Cannot find module 'rxjs-compat/Subject

### ISSUE THREAD

**Issue by Nagenderpratap** [sheikalthaf/ngu-carousel#79] opened 2018-08-29 07:09 UTC

**Comment by bperraud** [comment] 2018-08-30 08:28
Duplicate of https://github.com/sheikalthaf/ngu-carousel/issues/43

**Comment by sheikalthaf** [comment] 2018-09-08 16:39
@Nagenderpratap @bperraud Updated the carousel to angular 6. Thanks

**Closed by sheikalthaf** 2018-09-08 16:39 UTC
